language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  
  keep_history: true
  repo: ramclen/ramclen.github.io
  local_dir: projects/image-searcher
  on:
    branch: gh-pages
