language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
  - npm run post-build
deploy:
  provider: pages
  target_branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  
  repo: ramclen/ramclen.github.io
  local_dir: deploy
  verbose: true
  draft: true
  overwrite: true
  on:
    branch: master
